export default function Loading(props) {
    const css = `
    @keyframes ldio-rlgmai3ldl {
        0% { transform: scale(.85) }
        5% { transform: scale(1) }
       39% { transform: scale(.75) }
       45% { transform: scale(.9) }
       60% { transform: scale(.85) }
      100% { transform: scale(.8) }
    }
    .ldio-rlgmai3ldl > div {
      animation: ldio-rlgmai3ldl 0.9174311926605504s infinite cubic-bezier(0.215, 0.61, 0.355, 1);
      transform-origin: 50px 50px;
    }
    .ldio-rlgmai3ldl > div div {
      top: 36px;
      left: 30px;
      position: absolute;
      width: 40px;
      height: 40px;
      background: ${props.color};
      transform: rotate(45deg);
    }
    .ldio-rlgmai3ldl > div div:after, .ldio-rlgmai3ldl > div div:before {
      content: " ";
      position: absolute;
      display: block;
      width: 40px;
      height: 40px;
      background: ${props.color};
    }
    .ldio-rlgmai3ldl > div div:before {
      left: -26px;
      border-radius: 50% 0 0 50%;
    }
    .ldio-rlgmai3ldl > div div:after {
      top: -26px;
      border-radius: 50% 50% 0 0;
    } 
    .loadingio-spinner-heart-67kzgua68jp {
      width: 98px;
      height: 98px;
      display: inline-block;
      overflow: hidden;
      background: none;
    }
    .ldio-rlgmai3ldl {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(0.98);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-rlgmai3ldl div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
  `;
    return (
        <>
            <div className="loadingio-spinner-heart-67kzgua68jp">
                <div className="ldio-rlgmai3ldl">
                    <div>
                        <div></div>
                    </div>
                </div>
            </div>
            <style type="text/css">{css}</style>
        </>
    );
}
